name: Issue Details
on: issues
jobs:
  issue-details:
    runs-on: ubuntu-latest
    steps:
      - name: Print Issue
        run: |
          echo "A new issue was created by ${{ github.triggering_actor }}"
          echo "This issue was created at ${{ github.event.issue.created_at }}"
