name: Events Demo 1
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main # main
      - "dev-*" # dev-new
      - "feature/**" # feature/new or feature/new/button, etc

    # Can ignore changes to branch
    # branches-ignore:
    #   - "test/**" # this branch is ignored

    # Will only run workflow when changes made in src/** directory
    paths:
      - "src/**"

    # Will ignore changes made to docs/** directory
    # paths-ignore:
    #   - "docs/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."
